# [theme.templates.user.hyprland]
# input_path = '~/.config/matugen/templates.user.hyprland-colors.lua'
# output_path = '~/.config/hypr/hyprland/colors.lua'
# post_hook = 'hyprctl reload'

[theme.templates.user.kitty]
input_path = '~/.config/matugen/templates.user.kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = "kitty +kitten themes --reload-in=all 'Snow Dark'"

[theme.templates.user.rofi]
input_path = '~/.config/matugen/templates.user.rofi.colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[theme.templates.user.starship]
input_path = '~/.config/matugen/templates.user.starship-colors.toml'
output_path = '~/.config/starship/starship-matugen.toml'

[theme.templates.user.yazi]
input_path = '~/.config/matugen/templates.user.yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[theme.templates.user.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'
